name: Deploy Production Packages
on:
  release:
    types: [published]

jobs:
  publish:
    name: Pack and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Package
        run: dotnet pack Runly.Data/Runly.Data.csproj -c Release -o feeds/nuget

      - name: Push to Nuget
        run: find feeds/nuget -name '*.nupkg' | xargs -i dotnet nuget push {} -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}