name: Deploy Prerelease Packages
on: workflow_dispatch

jobs:
  publish:
    name: Pack and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Package Client
        run: dotnet pack Runly.Data/Runly.Data.csproj -c Release -o .

      - name: Push to GitHub Feed
        run: |
          dotnet tool install gpr -g
          gpr push *.nupkg -k ${{ secrets.GITHUB_TOKEN }}
