name: Deploy to Nuget

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'Runly.Data/Runly.Data.csproj'

jobs:
  publish:
    name: Pack and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release -p:Version=$VERSION

      - name: Package
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore -p:PackageVersion=$VERSION -c Release -o feeds/nuget

      - name: Push to Nuget
        run: find feeds/nuget -name '*.nupkg' | xargs -i dotnet nuget push {} -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}